examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/pytorch/modules/loss/seq_generation_loss.py
graph4nlp/pytorch/modules/utils/config_utils.py
graph4nlp/pytorch/modules/utils/generic_utils.py
graph4nlp/pytorch/test/seq_decoder/graph2seq/src/g2s_v2/core/utils/generic_utils.py
graph4nlp/pytorch/test/seq_decoder/graph2seq/src/g2s_v2/main.py

Fix warning when loading "yaml" files.
Fix warning in Graph2Seqloss.

fix warning

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/questions-help-support.md
.github/PULL_REQUEST_TEMPLATE.md

[Feature] add pr and issue template

---

graph4nlp/pytorch/data/dataset.py

Fixing charmap error seen for text classification on CAirline

---

examples/pytorch/semantic_parsing/graph2tree/jobs/config/new_constituency_graphsage_undirected.yaml
examples/pytorch/semantic_parsing/graph2tree/jobs/src/runner.py
graph4nlp/pytorch/data/dataset.py

add a missing option in ``dataset.py``: 
If all processed files are saved and option ``reuse_data`` is true, we reuse these processed files and do not run the ``_process`` function.

 [Feature] Add processed files reuse

---

.gitignore
docs/source/guide/construction.rst
docs/source/guide/construction/dependencygraphconstruction.rst
docs/source/guide/decoding.rst
docs/source/guide/decoding/stdrnndecoder.rst
docs/source/guide/evaluation.rst
graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py
graph4nlp/pytorch/test/graph_construction/test_dependency_construction.py

[Doc] Finish 1. dependency graph 2. stdrnndecoder 3. evaluation

---

docs/source/guide/classification.rst
docs/source/guide/classification/link_prediction.rst
docs/source/guide/classification/node_classification.rst
docs/source/guide/evaluation.rst
docs/source/guide/gnn.rst
docs/source/guide/gnn/graphsage.rst

Doc xiaojie

---

docs/source/guide/gnn/graphsage.rst
examples/pytorch/name_entity_recognition/conll.py
examples/pytorch/name_entity_recognition/inference.py
examples/pytorch/name_entity_recognition/main.py
examples/pytorch/name_entity_recognition/model.py

Inference xiaojie

---

examples/pytorch/text_classification/inference.py
examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/datasets/trec.py
graph4nlp/pytorch/modules/utils/generic_utils.py

- [] To the my best knowledge, examples are either not affected by this change,

[Feature] support inference workflow for text classification

---

docs/source/guide/decoding/stdrnndecoder.rst
docs/source/guide/decoding/stdtreedecoder.rst
graph4nlp/pytorch/models/graph2tree.py

[Doc] Polish doc for sequence decoding.

---

docs/source/guide/classification/graph_classification.rst
docs/source/guide/construction/dynamic_graph_construction.rst
docs/source/guide/construction/embedding_construction.rst
docs/source/guide/gnn/gat.rst
graph4nlp/pytorch/modules/graph_construction/embedding_construction.py

[Doc] Update dynamic graph construction, embedding construction, GAT, graph classification docs

---

docs/source/guide/construction/constituency_graph_construction.rst
docs/source/guide/decoding/stdtreedecoder.rst

refine doc constituency and tree decoder

[Doc] refine doc constituency and tree decoder

---

docs/source/guide/classification/link_prediction.rst
docs/source/guide/classification/node_classification.rst
docs/source/guide/gnn/graphsage.rst

Doc refine xiaojie

---

docs/source/index.rst

[Doc] Add fork badge

---

graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/datasets/geo.py
graph4nlp/pytorch/datasets/jobs.py
graph4nlp/pytorch/datasets/mathqa.py
graph4nlp/pytorch/datasets/mawps.py
graph4nlp/pytorch/models/graph2tree.py
graph4nlp/pytorch/modules/graph_construction/constituency_graph_construction.py
graph4nlp/pytorch/modules/prediction/generation/TreeBasedDecoder.py
graph4nlp/pytorch/modules/prediction/generation/attention.py
graph4nlp/pytorch/modules/utils/tree_utils.py

[Feature] code lint completed

---

docs/source/guide/graphdata/construct.rst
docs/source/guide/graphdata/manipulate.rst
docs/source/index.rst
graph4nlp/pytorch/data/dataset.py

[Doc] Added doc

---

docs/source/tutorial/semantic_parsing.rst
docs/source/tutorial/text_classification.rst

[Doc] updated doc tutorial: text classification and semantic parsing

---

examples/pytorch/kg_completion/WN18RR_main.py
examples/pytorch/kg_completion/evaluation.py
examples/pytorch/kg_completion/kinship_main.py
examples/pytorch/kg_completion/model.py
examples/pytorch/kg_completion/wrangle_KG.py
examples/pytorch/summarization/cnn/main.py
examples/pytorch/summarization/cnn/preprocess.py
examples/pytorch/summarization/cnn/rouge.py
examples/pytorch/summarization/cnn/test.py
graph4nlp/pytorch/datasets/cnn.py
graph4nlp/pytorch/modules/graph_construction/ie_graph_construction.py
graph4nlp/pytorch/modules/graph_embedding/gcn.py
graph4nlp/pytorch/modules/graph_embedding/ggnn.py
graph4nlp/pytorch/modules/loss/kg_loss.py
graph4nlp/pytorch/modules/prediction/classification/kg_completion/ComplEx.py
graph4nlp/pytorch/modules/prediction/classification/kg_completion/ComplExLayer.py
graph4nlp/pytorch/modules/prediction/classification/kg_completion/DistMult.py
graph4nlp/pytorch/modules/prediction/classification/kg_completion/DistMultLayer.py

Kgc sum code lint

---

examples/pytorch/semantic_parsing/graph2seq/args.py
examples/pytorch/semantic_parsing/graph2seq/evaluation.py
examples/pytorch/semantic_parsing/graph2seq/inference.py
examples/pytorch/semantic_parsing/graph2seq/main.py
examples/pytorch/semantic_parsing/graph2seq/utils.py
graph4nlp/pytorch/test/evaluation/test_accuracy.py

[Code Lint] code lint for semantic-parsing tests

---

examples/pytorch/math_word_problem/mathqa/src/config.py
examples/pytorch/math_word_problem/mathqa/src/evaluation.py
examples/pytorch/math_word_problem/mathqa/src/runner.py
examples/pytorch/math_word_problem/mawps/src/config.py
examples/pytorch/math_word_problem/mawps/src/evaluation.py
examples/pytorch/math_word_problem/mawps/src/runner.py
examples/pytorch/math_word_problem/mawps/src/test.py
examples/pytorch/semantic_parsing/graph2tree/geo/src/config.py
examples/pytorch/semantic_parsing/graph2tree/geo/src/evaluation.py
examples/pytorch/semantic_parsing/graph2tree/geo/src/runner.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/config.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/evaluation.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/runner.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/test.py

code lint for semantic parsing and math word problem

[Feature] code lint for sp&mwp

---

examples/pytorch/text_classification/inference.py
examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/pytorch/datasets/squad.py
graph4nlp/pytorch/datasets/trec.py
graph4nlp/pytorch/test/graph_classification/run_graph_classification.py
graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
graph4nlp/pytorch/test/graph_construction/run_dynamic_graph_construction.py
graph4nlp/pytorch/test/graph_construction/run_dynamic_text_graph_construction.py
graph4nlp/pytorch/test/graph_construction/test_constituecy_graph_construction.py
graph4nlp/pytorch/test/graph_construction/test_embedding_construction.py
graph4nlp/pytorch/test/graph_embedding/logger.py
graph4nlp/pytorch/test/graph_embedding/run_gat.py
graph4nlp/pytorch/test/graph_embedding/utils.py

[Lint] reformat example and test code

---

examples/pytorch/name_entity_recognition/conll.py
examples/pytorch/name_entity_recognition/conlleval.py
examples/pytorch/name_entity_recognition/dependency_graph_construction_without_tokenize.py
examples/pytorch/name_entity_recognition/inference.py
examples/pytorch/name_entity_recognition/line_graph_construction.py
examples/pytorch/name_entity_recognition/main.py
examples/pytorch/name_entity_recognition/model.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/modules/graph_embedding/graphsage.py
graph4nlp/pytorch/modules/loss/base.py
graph4nlp/pytorch/modules/loss/cross_entropy_loss.py
graph4nlp/pytorch/modules/loss/general_loss.py
graph4nlp/pytorch/modules/prediction/classification/base.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ConcatFeedForwardNN.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ConcatFeedForwardNNLayer.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ElementSum.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ElementSumLayer.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/StackedElementProd.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/StackedElementProdLayer.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/BiLSTMFeedForwardNN.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/BiLSTMFeedForwardNNLayer.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/FeedForwardNN.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/FeedForwardNNLayer.py
graph4nlp/pytorch/test/link_prediction/layers.py
graph4nlp/pytorch/test/link_prediction/link_prediction_test.py
graph4nlp/pytorch/test/link_prediction/model.py
graph4nlp/pytorch/test/link_prediction/optimizer.py
graph4nlp/pytorch/test/link_prediction/utils.py
graph4nlp/pytorch/test/node_classification/node_classification_test.py

format code

---

docs/source/tutorial/math_word_problem.rst

[Doc] mwp doc refine

---

graph4nlp/pytorch/modules/config/__init__.py
graph4nlp/pytorch/modules/config/graph_construction/__init__.py
graph4nlp/pytorch/modules/config/graph_embedding/__init__.py
graph4nlp/pytorch/modules/config/prediction/generation/__init__.py
graph4nlp/pytorch/modules/loss/__init__.py
graph4nlp/pytorch/modules/loss/coverage_loss.py
graph4nlp/pytorch/modules/loss/kg_loss.py
graph4nlp/pytorch/modules/loss/seq_generation_loss.py

[Lint] Code lint

---

examples/pytorch/text_classification/data/trec/data_preparation.py
graph4nlp/pytorch/modules/prediction/classification/graph_classification/__init__.py
graph4nlp/pytorch/modules/prediction/classification/graph_classification/avg_pooling.py
graph4nlp/pytorch/modules/prediction/classification/graph_classification/max_pooling.py

[Lint] fix code lint

---

graph4nlp/pytorch/modules/graph_construction/embedding_construction.py

Updated EmbeddingConstruction docstring to address #396 

[Doc string] updated EmbeddingConstruction docstring

---

examples/pytorch/text_classification/data/trec/data_preparation.py
examples/pytorch/text_classification/inference.py
examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/__init__.py
graph4nlp/pytorch/modules/graph_construction/__init__.py
graph4nlp/pytorch/modules/graph_construction/node_embedding_based_refined_graph_construction.py
graph4nlp/pytorch/modules/utils/padding_utils.py
graph4nlp/pytorch/test/graph_embedding/logger.py
graph4nlp/pytorch/test/graph_embedding/ogbn_test.py
graph4nlp/pytorch/test/utils.py

Fixed code lint warnings
- [] All changes have test coverage

[Lint] Fixed code lint warnings

---

examples/pytorch/math_word_problem/mathqa/src/runner.py
graph4nlp/pytorch/datasets/jobs.py
graph4nlp/pytorch/test/graph_construction/test_constituecy_graph_construction.py

[Fix] ci_shucheng

---

examples/pytorch/math_word_problem/mathqa/src/runner.py
examples/pytorch/math_word_problem/mawps/src/runner.py
examples/pytorch/semantic_parsing/graph2tree/geo/src/runner.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/runner.py
graph4nlp/pytorch/modules/graph_construction/constituency_graph_construction.py
graph4nlp/pytorch/modules/utils/tree_utils.py
graph4nlp/pytorch/test/generation/tree_decoder/test_tree_decoder.py

[Fix] Refine ci lint shucheng

---

examples/pytorch/name_entity_recognition/conlleval.py
examples/pytorch/name_entity_recognition/dependency_graph_construction_without_tokenize.py
examples/pytorch/name_entity_recognition/line_graph_construction.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ConcatFeedForwardNN.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ConcatFeedForwardNNLayer.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ElementSum.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/ElementSumLayer.py
graph4nlp/pytorch/modules/prediction/classification/link_prediction/StackedElementProd.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/FeedForwardNN.py
graph4nlp/pytorch/modules/prediction/classification/node_classification/FeedForwardNNLayer.py

fix flake8 ic

---

examples/pytorch/question_generation/run_question_generation_iclr.py
examples/pytorch/text_classification/inference.py
examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/pytorch/modules/graph_embedding/gat.py
graph4nlp/pytorch/modules/utils/bert_utils.py
graph4nlp/pytorch/test/graph_classification/run_graph_classification.py

[Lint] fixed lint warnings

---

graph4nlp/pytorch/test/data_structure/test_graphdata.py

[Code lint] fix code lint for graphdata unittest file

---

examples/pytorch/kg_completion/readme.md

update kgc readme

---

graph4nlp/pytorch/modules/utils/vocab_utils.py

[Fix] Fix bug in word emb size for pretrained WordEmbedding

---

examples/pytorch/name_entity_recognition/dependency_graph_construction_without_tokenize.py
examples/pytorch/name_entity_recognition/line_graph_construction.py

test after link

---

examples/pytorch/text_classification/config/CAirline/gat_bi_sep_dependency.yaml
examples/pytorch/text_classification/readme.md

update text clf readme

---

graph4nlp/pytorch/inference_wrapper/base.py
graph4nlp/pytorch/inference_wrapper/generator_inference_wrapper.py

[Fix] Fix the wrong argument ``graph_type`` in models

---

graph4nlp/pytorch/inference_wrapper/base.py
graph4nlp/pytorch/inference_wrapper/classifier_inference_wrapper.py
graph4nlp/pytorch/inference_wrapper/generator_inference_wrapper.py
graph4nlp/pytorch/inference_wrapper/generator_inference_wrapper_for_tree.py

[Fix] Fix argument bug in wrapper

---

examples/pytorch/name_entity_recognition/inference.py

add comment

---

examples/pytorch/summarization/cnn/main.py

[Fix] summarization model load bug

---

examples/pytorch/name_entity_recognition/conll.py
examples/pytorch/name_entity_recognition/dependency_graph_construction_without_tokenize.py
examples/pytorch/name_entity_recognition/line_graph_construction.py
examples/pytorch/name_entity_recognition/main.py
examples/pytorch/name_entity_recognition/model.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/inference_wrapper/classifier_inference_wrapper.py
graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py

Feature ner construction

---

setup.py

Updated version number to 0.5.5

---

examples/pytorch/question_generation/config/squad_split2/qg_g2s.yaml
examples/pytorch/question_generation/inference_advance.py
examples/pytorch/question_generation/main.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/datasets/squad.py
graph4nlp/pytorch/inference_wrapper/base.py
graph4nlp/pytorch/models/base.py
graph4nlp/pytorch/models/graph2seq.py
graph4nlp/pytorch/models/graph2tree.py
graph4nlp/pytorch/modules/utils/config_utils.py
setup.cfg

Updated config system to audo-load library yaml files and changed `graph_name` argument to `graph_construction_name` in QG demo, `SQuADDataset`, `Graph2Seq`, `Graph2Tree`, `Graph2XBase` and inference wrappers.

[Feature] Update config system to audo-load library yaml files and change graph_name to graph_construction_name

---

MANIFEST.in

[Bugfix] Included new YAML config files of the config system

---

examples/pytorch/math_word_problem/mawps/src/evaluation.py
examples/pytorch/semantic_parsing/graph2tree/jobs/config/new_dynamic_graphsage_undirected.json
examples/pytorch/semantic_parsing/graph2tree/jobs/config/new_dynamic_graphsage_undirected.yaml
examples/pytorch/semantic_parsing/graph2tree/jobs/config/semantic_parsing_with_tree_decoder.yaml
examples/pytorch/semantic_parsing/graph2tree/jobs/src/inference.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/inference_advance.py
examples/pytorch/semantic_parsing/graph2tree/jobs/src/runner.py
graph4nlp/pytorch/datasets/jobs.py
graph4nlp/pytorch/models/graph2tree.py

update config system for g2t & jobs
.## Checklist

[Feature] Feature update new config system for semantic parsing graph2tree

---

examples/pytorch/kg_completion/config/kgc_kinship.json
examples/pytorch/kg_completion/config/kgc_kinship.yaml
examples/pytorch/kg_completion/config/kgc_wn18rr.json
examples/pytorch/kg_completion/config/kgc_wn18rr.yaml
examples/pytorch/summarization/cnn/config/cnn.yaml
examples/pytorch/summarization/cnn/config/sum_g2s.json
examples/pytorch/summarization/cnn/config/sum_g2s.yaml
examples/pytorch/summarization/cnn/config/sum_g2s_ie.json
examples/pytorch/summarization/cnn/config/sum_g2s_ie.yaml
examples/pytorch/summarization/cnn/inference.py
examples/pytorch/summarization/cnn/inference_advance.py
examples/pytorch/summarization/cnn/main.py
examples/pytorch/summarization/cnn/readme.md
examples/pytorch/summarization/cnn/rouge.py

[Feature] Update config system for summarization

---

graph4nlp/pytorch/configs/prediction/generation/stdrnn.yaml
graph4nlp/pytorch/configs/prediction/generation/stdtree.yaml

Bug fix in decoder config templates.

[Feature] bug fix in decoder config templates

---

examples/pytorch/name_entity_recognition/inference.py
examples/pytorch/name_entity_recognition/readme.md

ner_readme

---

examples/pytorch/summarization/cnn/config/sum_g2s.yaml
examples/pytorch/summarization/cnn/config/sum_g2s_ie.yaml
examples/pytorch/summarization/cnn/main.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/datasets/cnn.py
graph4nlp/pytorch/modules/config/graph_construction/ie_graph_construction.yaml
graph4nlp/pytorch/modules/graph_construction/ie_graph_construction.py

[Feature] Fix Stanza ie

---

examples/pytorch/name_entity_recognition/config/dependency_graph_construction.yaml
examples/pytorch/name_entity_recognition/config/ner_inference.yaml
examples/pytorch/name_entity_recognition/conll.py
examples/pytorch/name_entity_recognition/dependency_graph_construction_without_tokenize.py
examples/pytorch/name_entity_recognition/inference_advance.py
examples/pytorch/name_entity_recognition/main.py

ner_stanza

---

examples/pytorch/question_generation/config/squad_split2/new_dependency_ggnn_bert.yaml
examples/pytorch/question_generation/config/squad_split2/qg.yaml
examples/pytorch/question_generation/inference_advance.py
examples/pytorch/question_generation/main.py
examples/pytorch/text_classification/config/trec/text_clf.yaml
examples/pytorch/text_classification/inference_advance.py
examples/pytorch/text_classification/run_text_classifier.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/datasets/squad.py
graph4nlp/pytorch/datasets/trec.py
graph4nlp/pytorch/modules/graph_construction/node_embedding_based_graph_construction.py
graph4nlp/pytorch/modules/graph_construction/node_embedding_based_refined_graph_construction.py

Unified dynamic graph construction callsites in dataset APIs and updated text classification and question generation applications.

unified dynamic graph construction callsites in dataset APIs and update text clf and qg applications

---

examples/pytorch/kg_completion/config/kgc_kinship.yaml
examples/pytorch/kg_completion/config/kgc_wn18rr.yaml
examples/pytorch/kg_completion/main.py
examples/pytorch/kg_completion/model.py

refine kgc config files

---

dev/requirements.txt
examples/pytorch/rgcn/rgcn.py
examples/pytorch/semantic_parsing/graph2seq/config/dependency_gcn_undirected.yaml
examples/pytorch/semantic_parsing/graph2seq/config/dependency_rgcn_undirected.yaml
examples/pytorch/semantic_parsing/graph2seq/config/train_dep_rgcn.json
examples/pytorch/semantic_parsing/graph2seq/main.py
examples/pytorch/semantic_parsing/graph2seq/main_rgcn.py
examples/pytorch/semantic_parsing/graph2seq/rgcn_lib/graph2seq.py
graph4nlp/pytorch/data/data.py
graph4nlp/pytorch/data/dataset.py
graph4nlp/pytorch/modules/graph_construction/dependency_graph_construction.py

[Feature] Add rgcn for semanticparsing, and fix GraphData bug for heterogeneous graph
